### ISSUE TITLE
Code out of date

### ISSUE THREAD

**Issue by aamcintosh** [naderelshehabi/dash-flask-login#2]
app.py:8: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
app.py:9: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

**Comment by naderelshehabi** [comment]
Fixed in latest commit 02e7cef8d11772d6bcf5709e47f7a68543dc2c6a
