### ISSUE TITLE
Under what license has this code been released?

### ISSUE THREAD

**Issue by kburchfiel** [naderelshehabi/dash-flask-login#3]
I really appreciate your putting this project together, as it will make it much easier for me to implement user authentication within my Dash projects. Under what license is the code being released? For instance, would we be permitted to use it in a commercial project? (I would of course plan to provide attribution.) Thank you!

**Comment by naderelshehabi** [comment]
Hi Kenneth.

Thanks for inquiring and raising this point.

Sure. Please go ahead and use the code in your commercial project, and feel free to modify it to fit your purpose if required.

I'll add a licence file to the repo to close this issue.

**Comment by kburchfiel** [comment]
Wonderful, thank you so much! I really appreciate it. A permissive license like the MIT one would be awesome, but the one you select is obviously your choice. 

Ken

**Comment by naderelshehabi** [comment]
MIT license added in latest commit 02e7cef8d11772d6bcf5709e47f7a68543dc2c6a
